### PR TITLE
Include 24.04 in base and build-base

### PR DESCRIPTION
**Pull request by dimaqq**
24.04 was released and these bases work for me.

### CODE REVIEW

**Comment by dimaqq** [comment]
P.S. I don't know how the `parts` markdown files are updated...

**Comment by babakks** [comment]
@dimaqq Huge thanks for this. Can you also please update the following locations so that we can safely land the PR?

1. https://github.com/babakks/vscode-rockcraft-ide/blob/434dda7eb2e0d395e38433e26936b105d90d2158/src/model/rock.ts#L92-L96

2. https://github.com/babakks/vscode-rockcraft-ide/blob/434dda7eb2e0d395e38433e26936b105d90d2158/schema/data/rockcraft.yaml/include/build-base.md#L4

3. https://github.com/babakks/vscode-rockcraft-ide/blob/434dda7eb2e0d395e38433e26936b105d90d2158/schema/data/rockcraft.yaml/include/base.md?plain=1#L4

**Comment by dimaqq** [comment]
Done!

**Comment by babakks** [comment]
Great. I'll merge this now, update the changelog and publish the new version (which would be `0.0.3`).

**Review by babakks — APPROVED** [review]

**Pull request merged**
